-- MySQL Script generated by MySQL Workbench
-- Fri Jun  5 15:17:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ese-search-api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ese-search-api` ;

-- -----------------------------------------------------
-- Schema ese-search-api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ese-search-api` DEFAULT CHARACTER SET utf8 ;
USE `ese-search-api` ;

-- -----------------------------------------------------
-- Table `ese-search-api`.`element_words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ese-search-api`.`element_words` ;

CREATE TABLE IF NOT EXISTS `ese-search-api`.`element_words` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NULL,
  `score` FLOAT NULL DEFAULT 0,
  `word_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_element_word_words_idx` (`word_id` ASC),
  CONSTRAINT `fk_element_word_words`
    FOREIGN KEY (`word_id`)
    REFERENCES `ese-search-api`.`words` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ese-search-api`.`search_words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ese-search-api`.`search_words` ;

CREATE TABLE IF NOT EXISTS `ese-search-api`.`search_words` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `type` ENUM('opendb_search_word', 'gg_analytics_word') CHARACTER SET 'utf8mb4' NOT NULL,
  `note` TEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `total_search` INT(11) NULL DEFAULT NULL,
  `page_view_per_search` FLOAT NULL DEFAULT NULL,
  `percentage_departures` FLOAT NULL DEFAULT NULL,
  `percentage_research` FLOAT NULL DEFAULT NULL,
  `time_after_search` INT(11) NULL DEFAULT NULL,
  `average_search_depth` FLOAT NULL DEFAULT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ese-search-api`.`word_relationships`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ese-search-api`.`word_relationships` ;

CREATE TABLE IF NOT EXISTS `ese-search-api`.`word_relationships` (
  `id` INT(11) UNSIGNED NOT NULL,
  `from_word_id` INT(11) UNSIGNED NOT NULL,
  `to_word_id` INT(11) UNSIGNED NOT NULL,
  `relationship_type` ENUM('other_name') NULL,
  `note` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_relationship_from_word_idx` (`from_word_id` ASC),
  INDEX `fk_relationship_to_word_idx` (`to_word_id` ASC),
  CONSTRAINT `fk_relationship_from_word`
    FOREIGN KEY (`from_word_id`)
    REFERENCES `ese-search-api`.`words` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relationship_to_word`
    FOREIGN KEY (`to_word_id`)
    REFERENCES `ese-search-api`.`words` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ese-search-api`.`words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ese-search-api`.`words` ;

CREATE TABLE IF NOT EXISTS `ese-search-api`.`words` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `eplus_id` VARCHAR(10) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `url` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `type` ENUM('artist', 'event') CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `note` TEXT CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `imported_at` DATETIME NOT NULL,
  `opendb_name` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `opendb_name_summary` VARCHAR(4000) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `opendb_word_description` VARCHAR(4000) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `opendb_word_description_search` VARCHAR(4000) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ese-search-api`.`words_advance_search`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ese-search-api`.`words_advance_search` ;

CREATE TABLE IF NOT EXISTS `ese-search-api`.`words_advance_search` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `average_users_per_day` FLOAT NULL DEFAULT NULL,
  `average_users_per_day_recently` FLOAT NULL DEFAULT NULL,
  `trending` FLOAT NULL DEFAULT NULL,
  `searches_last_30_days` FLOAT NULL DEFAULT NULL,
  `hits` INT(11) NULL DEFAULT NULL,
  `word_id` INT(11) UNSIGNED NOT NULL,
  `type` ENUM('popular_search', 'zero_hit') NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_words_advance_search_words1_idx` (`word_id` ASC),
  CONSTRAINT `fk_words_advance_search_words1`
    FOREIGN KEY (`word_id`)
    REFERENCES `ese-search-api`.`words` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ese-search-api`.`words_gg_analytics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ese-search-api`.`words_gg_analytics` ;

CREATE TABLE IF NOT EXISTS `ese-search-api`.`words_gg_analytics` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `total_search` INT(11) NULL DEFAULT NULL,
  `page_view_per_search` FLOAT NULL DEFAULT NULL,
  `percentage_departures` FLOAT NULL DEFAULT NULL,
  `percentage_research` FLOAT NULL DEFAULT NULL,
  `time_after_search` INT(11) NULL DEFAULT NULL,
  `average_search_depth` FLOAT NULL DEFAULT NULL,
  `word_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_words_gg_analytics_words_idx` (`word_id` ASC),
  CONSTRAINT `fk_words_gg_analytics_words`
    FOREIGN KEY (`word_id`)
    REFERENCES `ese-search-api`.`words` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ese-search-api`.`words_gg_keyword_planner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ese-search-api`.`words_gg_keyword_planner` ;

CREATE TABLE IF NOT EXISTS `ese-search-api`.`words_gg_keyword_planner` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `currency` ENUM('JPY', 'USD') CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `average_monthly_searches` FLOAT NULL DEFAULT NULL,
  `competition` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `competition_indexed_value` INT(11) NULL DEFAULT NULL,
  `top_of_page_bid_low_range` INT(11) NULL DEFAULT NULL,
  `top_of_page_bid_high_range` INT(11) NULL DEFAULT NULL,
  `ad_impression_share` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `organic_impression_share` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `organic_average_position` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `word_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_words_gg_keyword_planner_words1_idx` (`word_id` ASC),
  CONSTRAINT `fk_words_gg_keyword_planner_words1`
    FOREIGN KEY (`word_id`)
    REFERENCES `ese-search-api`.`words` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ese-search-api`.`words_gg_search_console`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ese-search-api`.`words_gg_search_console` ;

CREATE TABLE IF NOT EXISTS `ese-search-api`.`words_gg_search_console` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `click` INT(11) NULL DEFAULT NULL,
  `impression` INT(11) NULL DEFAULT NULL,
  `crt` FLOAT NULL DEFAULT NULL,
  `position` FLOAT NULL DEFAULT NULL,
  `word_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_words_gg_search_console_words1_idx` (`word_id` ASC),
  CONSTRAINT `fk_words_gg_search_console_words1`
    FOREIGN KEY (`word_id`)
    REFERENCES `ese-search-api`.`words` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ese-search-api`.`words_gg_trends_rasing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ese-search-api`.`words_gg_trends_rasing` ;

CREATE TABLE IF NOT EXISTS `ese-search-api`.`words_gg_trends_rasing` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `score` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `word_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_words_gg_trends_rasing_words1_idx` (`word_id` ASC),
  CONSTRAINT `fk_words_gg_trends_rasing_words1`
    FOREIGN KEY (`word_id`)
    REFERENCES `ese-search-api`.`words` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ese-search-api`.`words_gg_trends_related_queries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ese-search-api`.`words_gg_trends_related_queries` ;

CREATE TABLE IF NOT EXISTS `ese-search-api`.`words_gg_trends_related_queries` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT NULL,
  `word_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_words_gg_trends_related_queries_words1_idx` (`word_id` ASC),
  CONSTRAINT `fk_words_gg_trends_related_queries_words1`
    FOREIGN KEY (`word_id`)
    REFERENCES `ese-search-api`.`words` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ese-search-api`.`words_other_search`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ese-search-api`.`words_other_search` ;

CREATE TABLE IF NOT EXISTS `ese-search-api`.`words_other_search` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NULL,
  `score` FLOAT NULL DEFAULT 0,
  `word_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_words_other_search_words1_idx` (`word_id` ASC),
  CONSTRAINT `fk_words_other_search_words1`
    FOREIGN KEY (`word_id`)
    REFERENCES `ese-search-api`.`words` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ese-search-api`.`words_search_word`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ese-search-api`.`words_search_word` ;

CREATE TABLE IF NOT EXISTS `ese-search-api`.`words_search_word` (
  `word_id` INT(11) NOT NULL,
  `search_word_id` INT(11) NOT NULL,
  `relation_type` VARCHAR(45) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  INDEX `fk_words_relation_word_words1_idx` (`word_id` ASC),
  INDEX `fk_words_relation_word_words_relations1_idx` (`search_word_id` ASC),
  CONSTRAINT `fk_words_relation_word_words1`
    FOREIGN KEY (`word_id`)
    REFERENCES `ese-search-api`.`words` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
